### ISSUE TITLE
contact possible contributor to join projects on  sandbox

### ISSUE THREAD

**Issue by stefi-says** [OpenDataforWeb3/sandbox#13]
after we vote on the projects that we think are great to have as first round of projects to support on the sandbox we need to talk with it leads to join the Sandbox

**Comment by epowell101** [comment]
What do we want to talk to them about?

IMO we can go ahead and do a basic design incorporating what we think each project needs, where the projects are something like:
- Sybil Dashboard
- Sybil Legos
- Grant Dashboard
- Grant Legos

What I would ask them is as follows:
- thank you for contributing your code, we are strongly considering taking it forward
- would you like to help in this project?
- either way we will credit you for your contribution
- if you are actively involved in future activities such as:
     - product leadership
     - development
     - testing
     - developer relations
     - community support
- then you'll of course be in a position to receive any benefits such as future professional services revenues from any organizations that emerge to offer to support for the project we intended to take forward that incorporates your work

**Comment by sarob** [comment]
I suggest we start reviewing which sandbox teams to invite early this next week. 
 
We need to decide using either through GitHub issues (modeled after CNCF https://github.com/cncf/sandbox/issues/new/choose) or Discourse proposals (similar to gitcoin https://gov.gitcoin.co/t/gitcoin-community-proposal-gcp-template/134)

plus What do for sandbox teams I suggest here https://github.com/OpenDataforWeb3/governance/pull/6/files

**Comment by sarob** [comment]
I like moving to using discourse as proposal.opendatacommunity.org for the ODC Jedi to review and debate over a couple of days which hackathon submissions to invite as sandbox teams.
