### ISSUE TITLE
finish and compute community votes for projects to join the sandbox

### ISSUE THREAD

**Issue by stefi-says** [OpenDataforWeb3/sandbox#14]
compute votes of the community for first couple of project to invite and join sandbox

**Comment by epowell101** [comment]
The reason we funded hackathons focusing on Sybil legos and dashboards - and to some extent Grant screening and review and dashboards - is we know these are needed

IMO voting on the above isn't all that useful

We really need to pull together the pieces that we have from various hackathon contributions into a view of one or more projects that:
- gives visibility into round operators about the status of their rounds
- helps to screen grants
- help to assess intra round whether grants are legitimate

Taking into account both quadratic rounds and non quadratic rounds

**Comment by sarob** [comment]
I like moving to using discourse as ODC Jedi to review and debate over a couple of days which hackathon submissions to invite as sandbox teams.

1.  OminiAnalytics - Sybil Scorer
2. Stefi/ Poupou Legos python Package combined
3. Grant Reviwer
4. kikura & mitch legos submission combined
5. Kikura's dashboard submission
6. Umar's dashboard submission 

we configure our discourse very similar to https://gov.gitcoin.co using https://civs1.civs.us to start and then snapshot in future 

https://forum.opendatacommunity.org/t/sandbox-proposals/12/2

**Comment by stefi-says** [comment]
from a conversation the 14/03 general meeting, we decide to pivot the approach on how to initiate the first projects. The community already have a list of projects that are need form round operators. Therefore we will detail and collect requirements for this project and invite ex hackathon participants to join and contribute.
