### ISSUE TITLE
Organize links and usability for starting sandbox projects

### ISSUE THREAD

**Issue by stefi-says** [OpenDataforWeb3/sandbox#20]
Right now is kind hard to find the explanations for the current sandbox pipeline. there is no links to our form on discord and its not clear where to get information. 
we should move around and make our touch point connect in a way in every touch point user get redirect to where she/he can find information

**Comment by stefi-says** [comment]
started readme editing on this branch, open to contribution: https://github.com/OpenDataforWeb3/sandbox/blob/ac374d4e62fb6cee3769e59879905c6fd10a47bb/README.md

**Comment by sarob** [comment]
I posted an update to your branch. Check it out. Sean ***@***.*** On Mar 31, 2023, at 07:30, Stefi ***@***.***> wrote:﻿
started readme editing on this branch, open to contribution: https://github.com/OpenDataforWeb3/sandbox/blob/ac374d4e62fb6cee3769e59879905c6fd10a47bb/README.md
